title: Botium Toys: Scope, Goals, and Risk Assessment Report
description: An example of a risk assessment and posture analysis performed on a toy company
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
